conversation/urls.py
from django.urls import path

from .import views

app_name='conversation'

urlpatterns = [
    path('new/<int:item_pk>/',views.new_conversation,name='new'),
    path('',views.inbox,name='inbox'),
    path('<int:pk>/',views.detail,name='detail')
]

core/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .forms import LoginForm
app_name='core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(authentication_form = LoginForm ,template_name='core/login.html'), name='login'),
    path('logout/', views.logout_user, name='logout'),
]

dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
]

eMarket/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static  import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("core.urls")),
    path('item/',include("item.urls")),
    path('dashboard/',include("dashboard.urls")),
    path('inbox/',include("conversation.urls")),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

item/urls.py
from django.urls import path
from . import views

app_name = 'item'

urlpatterns = [
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('', views.items, name='items'),
    
]

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm) :
    username = forms.CharField(max_length=30,widget=forms.TextInput(attrs={'class':'form-control w-full py-3 px-6 rounded-xl','placeholder':'Username'}))
    password = forms.CharField(max_length=30,widget=forms.PasswordInput(attrs={'class':'form-control w-full py-3 px-6 rounded-xl','placeholder':'Password'}))
    
class SignupForm(UserCreationForm) :
    class Meta : 
        model = User 
        fields = ('username', 'email', 'password1', 'password2')
        
    username = forms.CharField(max_length=30,widget=forms.TextInput(attrs={'class':'form-control w-full py-3 px-6 rounded-xl','placeholder':'Username'}))
    email = forms.CharField(max_length=30,widget=forms.EmailInput(attrs={'class':'form-control w-full py-3 px-6 rounded-xl','placeholder':'Email'}))
    password1 = forms.CharField(max_length=30,widget=forms.PasswordInput(attrs={'class':'form-control w-full py-3 px-6 rounded-xl','placeholder':'Password'}))
    password2 = forms.CharField(max_length=30,widget=forms.PasswordInput(attrs={'class':'form-control w-full py-3 px-6 rounded-xl','placeholder':'Confirm Password'}))
    
    
    

core/views.py
from django.shortcuts import render,redirect
from item.models import Item,Category
from .forms import SignupForm
from django.contrib.auth.decorators import login_required 
from django.contrib.auth import logout

# Create your views here.
def index(request) :
    items=Item.objects.filter(is_sold=False)[0:6]
    categories=Category.objects.all()

    return render(request, 'core/index.html',{'items':items,'categories':categories})

def contact(request) : 
    return render(request, 'core/contact.html',{})
    
def signup(request) :
    
    if request.method=='POST' :
        form=SignupForm(request.POST)
        print("hi")
        if form.is_valid() :
            form.save()
            return redirect('/login/')
    else : 
        form=SignupForm()
    return render(request, 'core/signup.html',{'form':form})

@login_required
def logout_user(request) :
    logout(request)
    return redirect('core:index')

core/templates/core/base.html
<!doctype html >

<html>
    <head>
        <meta charset="utf-8">
        <meta name= "viewport" content="width=device-width, initial-scale=1.0">
        
        <script src = "https://cdn.tailwindcss.com"></script>

        <title>{% block title %}{%endblock%} | eMart</title>
    </head>
    {% load static %}
    <body>

        <nav class = "py-6 px-6 justify-between items-center border-b border-gray-200 flex flex-row reverse">
            <a href = "/"><img src = "{% static '/media/logo.png'%}" height="50" width="100"></a>
            
            <div class= "space-x-6">
                <a href = "{% url 'item:new' %}" class = "px-3 text-lg font-semibold hover:text-gray-500">Sell Item</a>
                <a href = "{% url 'item:items' %}" class = "text-lg font-semibold hover:text-gray-500">Browse</a>

                {% if request.user.is_authenticated %}
                    <a href = "{% url 'core:logout' %}" class = "px-6 py-3 text-lg font-semibold bg-cyan-500 text-white rounded-xl hover:bg-cyan-700" > Logout</a>
                    <a href = "{% url 'conversation:inbox' %}" class = "px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700" > Inbox </a>
                    <a href = "{% url 'dashboard:index' %}" class = "px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700" > Dash Board</a>
                {% else %}
                    <a href = "{% url 'core:signup' %}" class = "px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700" > Sign Up </a>
                    <a href = "{% url 'core:login'%}" class = "px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700" > Log In </a>
                {% endif %}
                
            </div>
        </nav>

        <div class = "px-6 py-6">
            {%block content %}


            {% endblock %}
        </div>

        <footer class = "py-6 px-6 flex-justify-between bg-gray-800" > 
            <div class="flex flex-row">
                <div class = "pr-10 w-2/3">
                    <h3 class = "mb-5 font-semibold text-gray-400"> About </h3>

                    <p class= "text-lg text-gray-500">Blah blah blah blah Blah blah blah blah Blah blah blah blah Blah blah blah blah Blah blah blah blah Blah blah blah blah Blah blah blah blah Blah blah blah blah Blah blah blah blah  </p>
                </div>

                <div class = "w-1/3" >
                    <h3 class = "mb-5 font-semibold text-gray-400"> Menu </h3>
                    
                    <ul class= "space-y-2">
                        <li><a href= "#" class = "text-lg text-teal-500 hover:text-teal-700">About</a></li>
                        <li><a href= "{% url 'core:contact' %}" class = "text-lg text-teal-500 hover:text-teal-700">Contact</a></li>
                        <li><a href= "#" class = "text-lg text-teal-500 hover:text-teal-700">Privacy policy</a></li>
                        <li><a href= "#" class = "text-lg text-teal-500 hover:text-teal-700">Terms of use</a></li>
                    </ul>
                </div>
            </div>
        </footer>
    </body>
</html>

core/templates/core/contact.html
{%extends 'core/base.html'%}
{%block title%}
    Contact
{%endblock%}

{%block content%}
    <h1>The Contact Page</h1>
{%endblock%}

core/templates/core/index.html
{%extends 'core/base.html'%}
{%block title%}
    Welcome
{%endblock%}

{%block content%}
{% if request.user.is_authenticated %}
    <div class = "mx-auto text-lg text-gray-500 text-center">Welcome {{request.user.username}} ! </div>
{% endif %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl ">
        <h1 class="mb-12 text-4xl text-center">Newest Items</h1>

        <div class="grid grid-cols-3 gap-3">
            {% for item in items %}
                <div>
                    <a href="{% url 'item:detail' pk=item.id %}">
                    <div>
                        <img src = "{{item.image.url}}" class= "rounded-t-xl">
                    </div>
                    <div class="p-6 bg-white rounder-b-xl">
                        <h2 class =" text-2xl">{{item.name}}</h2>
                        <p class="text-gray-500">Price : ${{item.price}}</p>
                    </div>
                    </a>
                </div>
            {% endfor%}
        </div>
    </div>

    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl ">
        <h1 class="mb-12 text-4xl text-center">Categories</h1>

        <div class="grid grid-cols-3 gap-3">
            {%for category in categories%}
                <div>
                    <a href="#"></a>
                    <div class="p-6 bg-white rounder-b-xl">
                        <h2 class =" text-2xl">{{category.name}}</h2>
                        <p class="text-gray-500">{{category.items.count}}</p>
                    </div>
                </div>
            {%endfor%}
        </div>
    </div>

{%endblock%}

core/templates/core/login.html
{%extends 'core/base.html' %}

{%block title%}Login{%endblock%}

{%block content%}

<div class ="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class = 'mb-6 text-4xl font-semibold'> Login </h1>

    <form method="post" action =".">
        {% csrf_token %}
        <div class ="mb-3">
            <label class =" inline-block mb-2 text-xl">Username</label><br>
            {{ form.username }}
        </div>

        <div class ="mb-3">
            <label class =" inline-block mb-2 text-xl">Password</label><br>
            {{ form.password }}
        </div>

        <br>

        {% if form.errors or form.non_field_errors %}
            <div class = " mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{field.errors}}
                {%endfor%}

                {{ form.non_field_errors }}
            </div>
        {% endif%}
        <button type ="submit" class ="py-3 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
</div>

{%endblock%}

core/templates/core/signup.html
{%extends 'core/base.html' %}

{%block title%}Signup{%endblock%}

{%block content%}

<div class ="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class = 'mb-6 text-4xl font-semibold'> Sign up </h1>

    <form method="post" action =".">
        {% csrf_token %}
        <div class ="mb-3">
            <label class =" inline-block mb-2 text-xl">Username</label><br>
            {{ form.username }}
        </div>

        <div class ="mb-3">
            <label class =" inline-block mb-2 text-xl">Email</label><br>
            {{ form.email }}
        </div>

        <div class ="mb-3">
            <label class =" inline-block mb-2 text-xl">Password</label><br>
            {{ form.password1 }}
        </div>

        <div class ="mb-3">
            <label class =" inline-block mb-2 text-xl">Confirm password</label><br>
            {{ form.password2 }}
        </div>

        <br>

        {% if form.errors or form.non_field_errors %}
            <div class = " mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{field.errors}}
                {%endfor%}

                {{ form.non_field_errors }}
            </div>
        {% endif%}
        <button type ="submit" class ="py-3 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
</div>

{%endblock%}